// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.3";

// src/lib/mcp/tools/buscar-jurisprudencia.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.4";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/buscar-jurisprudencia.ts
var buscar_jurisprudencia_default = defineTool({
  name: "buscar_jurisprudencia",
  title: "Buscar jurisprud\xEAncia",
  description: "Busca decis\xF5es judiciais no acervo do Honor\xEDfico por texto livre, com filtros opcionais de tribunal, UF e inst\xE2ncia. Retorna ementa, \xF3rg\xE3o julgador e link da fonte.",
  inputSchema: {
    consulta: z.string().trim().min(2).describe("Termos da busca, por exemplo: dano moral negativa\xE7\xE3o indevida"),
    tribunal: z.string().trim().optional().describe("Sigla do tribunal, por exemplo TJSP"),
    uf: z.string().trim().length(2).optional().describe("UF de duas letras, por exemplo SP"),
    instancia: z.string().trim().optional().describe("Inst\xE2ncia da decis\xE3o"),
    limite: z.number().int().min(1).max(20).default(10).describe("Quantidade de resultados")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ consulta, tribunal, uf, instancia, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("search_decisions", {
      search_query: consulta,
      filter_tribunal: tribunal ?? void 0,
      filter_uf: uf ? uf.toUpperCase() : void 0,
      filter_instancia: instancia ?? void 0,
      result_limit: limite
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const itens = (data ?? []).map((d) => ({
      id: d.id,
      tribunal: d.tribunal,
      orgao_julgador: d.orgao_julgador,
      numero_processo: d.numero_processo,
      data_decisao: d.data_decisao,
      relator: d.relator,
      ementa: typeof d.ementa === "string" ? d.ementa.slice(0, 1200) : null,
      resultado: d.resultado,
      fonte: d.source_url
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(itens, null, 2) }],
      structuredContent: { total: itens.length, itens }
    };
  }
});

// src/lib/mcp/tools/ver-decisao.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z as z2 } from "npm:zod@^3.25.76";
var ver_decisao_default = defineTool2({
  name: "ver_decisao",
  title: "Ver decis\xE3o",
  description: "Retorna os dados completos de uma decis\xE3o do acervo a partir do seu identificador, incluindo ementa, legisla\xE7\xE3o citada e link da fonte.",
  inputSchema: {
    id: z2.string().uuid().describe("Identificador da decis\xE3o, obtido em buscar_jurisprudencia")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("decisions").select(
      "id,tribunal,orgao_julgador,comarca,uf,instancia,numero_processo,data_decisao,relator,tipo_decisao,resultado,resultado_descricao,ementa,resumo_ia,legislacao_citada,jurisprudencias_citadas,temas_juridicos,source,source_url"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Decis\xE3o n\xE3o encontrada" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { decisao: data }
    };
  }
});

// src/lib/mcp/tools/buscar-sumulas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z as z3 } from "npm:zod@^3.25.76";
var buscar_sumulas_default = defineTool3({
  name: "buscar_sumulas",
  title: "Buscar s\xFAmulas",
  description: "Busca s\xFAmulas e enunciados no acervo do Honor\xEDfico por texto livre, com filtros opcionais de tribunal e \xE1rea do direito.",
  inputSchema: {
    consulta: z3.string().trim().min(2).describe("Termos da busca, por exemplo: prescri\xE7\xE3o consumidor"),
    tribunal: z3.string().trim().optional().describe("Sigla do tribunal, por exemplo STJ"),
    area: z3.string().trim().optional().describe("\xC1rea do direito"),
    limite: z3.number().int().min(1).max(20).default(10).describe("Quantidade de resultados")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ consulta, tribunal, area, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("search_sumulas", {
      search_query: consulta,
      filter_tribunal: tribunal ?? void 0,
      filter_area: area ?? void 0,
      result_limit: limite
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const itens = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(itens, null, 2) }],
      structuredContent: { total: itens.length, itens }
    };
  }
});

// src/lib/mcp/tools/meu-historico.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.3";
import { z as z4 } from "npm:zod@^3.25.76";
var meu_historico_default = defineTool4({
  name: "meu_historico",
  title: "Meu hist\xF3rico",
  description: "Lista os itens salvos na conta de quem est\xE1 conectado: an\xE1lises, peti\xE7\xF5es e c\xE1lculos, do mais recente para o mais antigo.",
  inputSchema: {
    tipo: z4.enum(["analises", "peticoes", "calculos"]).default("analises").describe("Tipo de item do hist\xF3rico"),
    limite: z4.number().int().min(1).max(50).default(10).describe("Quantidade de itens")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tipo, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const tabela = tipo === "analises" ? "analyses" : tipo === "peticoes" ? "petitions" : "calculos";
    const colunas = tipo === "analises" ? "id,created_at,file_name,input_text,result" : tipo === "peticoes" ? "id,created_at,petition_type,generated_text" : "*";
    const { data, error } = await supabase.from(tabela).select(colunas).order("created_at", { ascending: false }).limit(limite);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const itens = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(itens, null, 2) }],
      structuredContent: { tipo, total: itens.length, itens }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hfhzkvuoywgxjklpiydq";
var mcp_default = defineMcp({
  name: "honorifico",
  title: "Honor\xEDfico",
  version: "0.1.0",
  instructions: "Ferramentas do Honor\xEDfico, plataforma de pesquisa jur\xEDdica brasileira. Use buscar_jurisprudencia para localizar decis\xF5es com fonte, ver_decisao para o inteiro teor dos metadados, buscar_sumulas para enunciados e meu_historico para os itens salvos na conta conectada. Cite sempre o link da fonte e nunca invente n\xFAmero de processo ou precedente.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [buscar_jurisprudencia_default, ver_decisao_default, buscar_sumulas_default, meu_historico_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
